# IMAGES
BACKGROUND = "assets/images/background.png"
LION_BLACK = "assets/images/lion_black.png"
GIRAFFE_BLACK = "assets/images/giraffe_black.png"
ELEPHANT_BLACK = "assets/images/elephant_black.png"
RHINO_BLACK = "assets/images/rhino_black.png"
CHEETAH_BLACK = "assets/images/cheetah_black.png"
HYENA_BLACK = "assets/images/hyena_black.png"
LION_COLOR = "assets/images/lion_color.png"
GIRAFFE_COLOR = "assets/images/giraffe_color.png"
ELEPHANT_COLOR = "assets/images/elephant_color.png"
RHINO_COLOR = "assets/images/rhino_color.png"
CHEETAH_COLOR = "assets/images/cheetah_color.png"
HYENA_COLOR = "assets/images/hyena_color.png"
